GET http://localhost:3000/pokemon

###

GET http://localhost:3000/pokemon/query?attribute=electric

###

POST http://localhost:3000/pokemon
Content-Type: application/json

{
    "name": "Scyther",
    "hp": 100,
    "attribute1": "grass",
    "attribute2": "insect"
}

###

PUT http://localhost:3000/pokemon/Scyther
Content-Type: application/json

{
    "name": "d;khsdfkjhsdf",
    "completedDifferent": "abc"
}

###

PATCH http://localhost:3000/pokemon/Scyther
Content-Type: application/json

{
    "name": "d;khsdfkjhsdf",
    "hp": 666
}

###

DELETE http://localhost:3000/pokemon/Scyther